### ISSUE TITLE
Installation Documentation for ghc and stack/cabal

### ISSUE THREAD

**Issue by sjaster** [fsr/calendargen#5]
For noobs like @heisig and me the installation of ghc and stack or cabal is quite too hard. There are so many packages, too many packages. Just WOW -- we definitly need a guide for that tho.

oh wait maybe we got it... nevermind we found that there are still some other errors out in the dark.

**Comment by Feliix42** [comment]
Have you tried [this](https://wiki.archlinux.org/index.php/Haskell#Problems_with_linking)? :smile:

**Comment by sjaster** [comment]
finally installed calendargen. It's even installing the package but the command does not exist for usage

**Comment by JustusAdam** [comment]
Update your $PATH. If you used stack then add `~/.local/bin` to your $PATH

**Comment by sjaster** [comment]
@kalinni generated it :D
